sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sanketh1701/docker-react-2020 -f Dockerfile.dev .

script:
  - docker run -e CI=true sanketh1701/docker-react-2020 npm run test
    